version: "2"
run:
  timeout: "1m"
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
linters:
  default: all
  disable:
    - wsl
    - nolintlint
    - contextcheck
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - mnd
    - nestif
    - nlreturn
    - revive
    - varnamelen
    - canonicalheader # Disabled due to false positives with http header Hx-Request
  settings:
    gocognit:
      min-complexity: 20
    cyclop:
      max-complexity: 10
      package-average: 0
    interfacebloat:
      max: 10
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
      shorten-comments: true
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  uniq-by-line: true
  whole-files: false
